In [2]:
import numpy as np

In [10]:
array=np.array([1, 3, 5, 3, 7, 1, 9, 3])
array.tolist()

[1, 3, 5, 3, 7, 1, 9, 3]

In [16]:
v = np.random.randint(2, 10, size=(3,3))
print(v)
result = np.trace(v)
print(result)

[[6 4 7]
 [9 7 9]
 [5 9 3]]
16


In [8]:
w = np.random.randint(1,40, size=(3,3))
x = 16
print(w)
print( w[w>x])

[[21  7 12]
 [33  4 20]
 [26 30 33]]
[21 33 20 26 30 33]


In [18]:
A = np.array([[14,9],[2,7]])
B = np.array([[5,6],[7,8]])
C = np.add(A,B)
print(C)

[[19 15]
 [ 9 15]]


In [12]:
U = np.random.randint(1,17, size=(2,2))
Y = U - U.mean(axis=1, keepdims=True)
print(Y)

[[ 6.5 -6.5]
 [ 2.  -2. ]]
